site_name: PharmaPy API

nav:
  - Introduction: index.md
  - Reference API: api.md


theme:
  name: material
  palette:
    scheme: pharmapy
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - content.code.copy
    - content.tabs.link
    - toc.integrate
    - navigation.top
extra_css:
  - custom.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
